worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        location = / {
            rewrite ^ /static/index.html last;
        }

        location / {
            try_files $uri =404;
        }

        location /yt {
            return 301 https://www.youtube.com/@lyciberi;
        }

        location /youtube {
            return 301 https://www.youtube.com/@lyciberi;
        }

        location /t {
            return 301 https://twitter.com/lyciberi;
        }

        location /x {
            return 301 https://twitter.com/lyciberi;
        }

        location /twt {
            return 301 https://twitter.com/lyciberi;
        }

        location /twitter {
            return 301 https://twitter.com/lyciberi;
        }

        location /ttv {
            return 301 https://www.twitch.tv/lyciberi;
        }

        location /twitch {
            return 301 https://www.twitch.tv/lyciberi;
        }

        location /discord {
            return 301 https://discord.com/invite/Ywh4xN6YFX;
        }

        location /bsky {
            return 301 https://bsky.app/profile/lyciberi.bsky.social;
        }

        location /bluesky {
            return 301 https://bsky.app/profile/lyciberi.bsky.social;
        }

        location /tiktok {
            return 301 https://www.tiktok.com/@lyciberi;
        }

        location /static/ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
}
